# Generated by Django 6.0.4 on 2026-04-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_query', models.CharField(default='subject:(deal OR property OR wholesale)', max_length=255)),
                ('whatsapp_token', models.TextField(blank=True)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=255)),
                ('whatsapp_to_number', models.CharField(blank=True, max_length=50)),
                ('min_beds', models.FloatField(default=2)),
                ('min_baths', models.FloatField(default=1)),
                ('max_price', models.IntegerField(default=150000)),
                ('min_year_built', models.IntegerField(default=1970)),
                ('min_sqft', models.IntegerField(default=1300)),
                ('allowed_zip_codes', models.TextField(blank=True, default='')),
                ('flip_arv_multiplier', models.FloatField(default=0.7)),
                ('brrrr_loan_multiplier', models.FloatField(default=0.75)),
                ('min_flip_profit', models.IntegerField(default=30000)),
                ('max_brrrr_cash_left', models.IntegerField(default=5000)),
                ('rehab_cost_per_sqft', models.IntegerField(default=35)),
                ('offer_template', models.TextField(default='Hi,\n\nThank you for sending this deal.\n\nBased on our numbers, we would be interested at {{ mao }}.\n\nThanks')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('beds', models.FloatField(blank=True, null=True)),
                ('baths', models.FloatField(blank=True, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('arv', models.IntegerField(blank=True, null=True)),
                ('rehab_cost', models.IntegerField(blank=True, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('mao', models.IntegerField(blank=True, null=True)),
                ('flip_profit', models.IntegerField(blank=True, null=True)),
                ('brrrr_cash_left', models.IntegerField(blank=True, null=True)),
                ('qualifies', models.BooleanField(default=False)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
