# Generated by Django 6.0.4 on 2026-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(blank=True, max_length=255)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('snippet', models.TextField(blank=True)),
                ('status', models.CharField(default='found', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('deal_created', models.BooleanField(default=False)),
                ('qualifies', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
