# Generated by Django 6.0.4 on 2026-05-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_emailreadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='custom_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='important_notes',
            field=models.TextField(blank=True),
        ),
    ]
