# Generated by Django 6.0.4 on 2026-05-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_custom_identifier_deal_important_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token_json', models.JSONField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
