# Generated by Django 6.0.4 on 2026-05-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_gmailaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='raw_email_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
