# Generated by Django 6.0.4 on 2026-05-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_deal_raw_email_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='difflib_confidence_threshold',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='deal',
            name='difflib_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='is_labeled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='is_potential_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='label_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='matched_example_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='matched_example_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='send_to_llm',
            field=models.BooleanField(default=False),
        ),
    ]
