# Generated by Django 6.0.4 on 2026-05-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_appsettings_difflib_confidence_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='html_body',
            field=models.TextField(blank=True),
        ),
    ]
