# Generated by Django 6.0.4 on 2026-05-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_deal_html_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='gmail_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
