# Generated by Django 6.0.4 on 2026-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_deal_gmail_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='llm_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='llm_is_valid_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='llm_reason',
            field=models.TextField(blank=True),
        ),
    ]
