# Generated by Django 6.0.4 on 2026-06-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_deal_llm_checked_deal_llm_is_valid_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='llm_missing_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
