# Generated by Django 6.0.4 on 2026-06-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_deal_llm_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='llm_required_categories',
            field=models.TextField(default='Location/address/city/zip\n    Price/list price/asking price\n    Year built\n    Square footage\n    ARV / after repair value\n    Beds and baths\n    Taxes\n    Rehab estimate\n    Rent estimate\n    Suggested offer'),
        ),
    ]
