# Generated by Django 6.0.4 on 2026-06-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_appsettings_llm_required_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='math_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='math_qualifies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='math_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='zip_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
