# Generated by Django 6.0.4 on 2026-06-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_deal_math_checked_deal_math_qualifies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('arv', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rehab_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('beds', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('suggested_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('zip_allowed', models.BooleanField(default=False)),
                ('mao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('flip_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('brrrr_cash_left', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qualifies_flip', models.BooleanField(default=False)),
                ('qualifies_brrrr', models.BooleanField(default=False)),
                ('qualifies', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('raw_llm_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='deals.deal')),
            ],
        ),
    ]
