# Generated by Django 6.0.4 on 2026-06-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_propertylisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('beds', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('sold_date', models.CharField(blank=True, max_length=100)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('source_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comps', to='deals.propertylisting')),
            ],
        ),
    ]
